using Hedron.Core.ECS;
using Hedron.Core.System;
using System.Collections.Generic;

namespace Hedron.Core.ECS.Components
{
	/// <summary>
	/// Component for area-specific data
	/// </summary>
	public class AreaDataComponent : IComponent
	{
		/// <summary>
		/// The rate of respawning in ticks
		/// </summary>
		public int RespawnRate { get; set; } = Constants.AREA_MANUAL_RESPAWN;

		/// <summary>
		/// List of spawnable mob prototype IDs for random spawning
		/// </summary>
		public List<uint> SpawnableMobIds { get; set; } = new List<uint>();

		/// <summary>
		/// List of curated item prototype IDs that can drop in this area
		/// </summary>
		public List<uint> CuratedItemIds { get; set; } = new List<uint>();

		/// <summary>
		/// List of autogenerated prototype mob IDs for this area
		/// </summary>
		public List<uint> AutogeneratedPrototypeMobIds { get; set; } = new List<uint>();

		/// <summary>
		/// Weather conditions in the area
		/// </summary>
		public string Weather { get; set; } = "Clear";

		/// <summary>
		/// Temperature in the area (affects gameplay)
		/// </summary>
		public int Temperature { get; set; } = 20;

		/// <summary>
		/// Whether this area allows PvP combat
		/// </summary>
		public bool PvPEnabled { get; set; } = false;

		/// <summary>
		/// Difficulty modifier for the area
		/// </summary>
		public float DifficultyModifier { get; set; } = 1.0f;
	}
}