using Core.ECS.Properties;

namespace Hedron.Core.ECS.Components
{
    /// <summary>
    /// Component containing basic identity information for entities
    /// </summary>
    public class IdentityComponent : IComponent
    {
        /// <summary>
        /// The name of the entity
        /// </summary>
        public string Name { get; set; } = "[name]";

        /// <summary>
        /// The Short Description of the entity
        /// </summary>
        public string ShortDescription { get; set; } = "[short]";

        /// <summary>
        /// The Long Description of the entity
        /// </summary>
        public string LongDescription { get; set; } = "[long]";

        /// <summary>
        /// The Tier of the entity
        /// </summary>
        public Tier Tier { get; set; } = new Tier();

        /// <summary>
        /// Whether this entity was automatically generated
        /// </summary>
        public bool WasAutoGenerated { get; set; }
    }
}