using Hedron.Data;
using Hedron.Core.System;
using Hedron.Core.ECS;
using Hedron.Core.ECS.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using Core.Modules.Factory;
using Core.Modules.Locale;
using Core.ECS;
using Core.ECS.Properties;
using Core.ECS.Properties.Effects;
using Core.ECS.Entities.Container;

namespace Core.ECS.Entities.Base
{
	/// <summary>
	/// Base entity class - now purely ECS-based
	/// Use EntityFactory to create entities with specific component compositions
	/// </summary>
	public class Entity : CacheableObject, ICopyableObject<Entity>, IEntity, IEffectObservable, IEntityChildOfRoom, IEntityChildOfArea
	{
		// Legacy events for compatibility
		public event EventHandler<EffectEventArgs> EffectAdded;
		public event EventHandler<EffectEventArgs> EffectRemoved;

		/// <summary>
		/// Gets the Effects on the entity from EffectsComponent
		/// </summary>
		public IReadOnlyCollection<Effect> Effects
		{
			get
			{
				if (Instance.HasValue)
				{
					var effectsComponent = EcsManager.World.GetComponent<EffectsComponent>(Instance.Value);
					if (effectsComponent != null)
						return effectsComponent.Effects.AsReadOnly();
				}
				return new List<Effect>().AsReadOnly();
			}
		}

		/// <summary>
		/// Gets the name of the entity from IdentityComponent
		/// </summary>
		public string Name 
		{ 
			get 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						return identityComponent.Name;
				}
				return "[entity]";
			}
			set 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						identityComponent.Name = value;
				}
			}
		}

		/// <summary>
		/// Gets the Short Description of the entity from IdentityComponent
		/// </summary>
		public string ShortDescription 
		{ 
			get 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						return identityComponent.ShortDescription;
				}
				return "[entity]";
			}
			set 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						identityComponent.ShortDescription = value;
				}
			}
		}

		/// <summary>
		/// Gets the Long Description of the entity from IdentityComponent
		/// </summary>
		public string LongDescription 
		{ 
			get 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						return identityComponent.LongDescription;
				}
				return "You see an entity.";
			}
			set 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						identityComponent.LongDescription = value;
				}
			}
		}

		/// <summary>
		/// Gets the Tier of the entity from IdentityComponent
		/// </summary>
		public Tier Tier 
		{ 
			get 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						return identityComponent.Tier;
				}
				return new Tier();
			}
			protected set 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						identityComponent.Tier = value;
				}
			}
		}

		/// <summary>
		/// Gets whether this entity was automatically generated from IdentityComponent
		/// </summary>
		public bool WasAutoGenerated 
		{ 
			get 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						return identityComponent.WasAutoGenerated;
				}
				return false;
			}
			set 
			{
				if (Instance.HasValue)
				{
					var identityComponent = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
					if (identityComponent != null)
						identityComponent.WasAutoGenerated = value;
				}
			}
		}

		/// <summary>
		/// Default constructor
		/// </summary>
		public Entity() : base()
		{
			// No automatic component initialization - use EntityFactory instead
		}

		/// <summary>
		/// Adds an Effect to the entity via EffectsComponent
		/// </summary>
		/// <param name="effect">The Effect to add</param>
		/// <param name="stack">Whether to stack the Effect. If false, the Effect will overwrite any Effect(s) of the same name.</param>
		public virtual void AddEffect(Effect effect, bool stack)
		{
			if (Instance.HasValue)
			{
				var effectsComponent = EcsManager.World.GetComponent<EffectsComponent>(Instance.Value);
				if (effectsComponent != null)
				{
					if (!stack)
					{
						// Remove existing effects with the same name
						effectsComponent.Effects.RemoveAll(e => e.Name == effect.Name);
					}
					effectsComponent.Effects.Add(effect);
					OnEffectAdded(new EffectEventArgs(effect));
				}
			}
		}

		/// <summary>
		/// Invokes the EffectAdded event
		/// </summary>
		/// <param name="args">The event args</param>
		protected virtual void OnEffectAdded(EffectEventArgs args)
		{
			var handler = EffectAdded;
			if (handler != null)
				handler.Invoke(this, args);
		}

		/// <summary>
		/// Removes all Effects of the given name
		/// </summary>
		/// <param name="effectName">The Effect name to remove</param>
		public void RemoveEffect(string effectName)
		{
			if (Instance.HasValue)
			{
				var effectsComponent = EcsManager.World.GetComponent<EffectsComponent>(Instance.Value);
				if (effectsComponent != null)
				{
					var effectsToRemove = effectsComponent.Effects.Where(e => e.Name == effectName).ToList();
					foreach (var effect in effectsToRemove)
					{
						effectsComponent.Effects.Remove(effect);
						OnEffectRemoved(new EffectEventArgs(effect));
					}
				}
			}
		}

		/// <summary>
		/// Removes a specific Effect at the given index in Effects
		/// </summary>
		/// <param name="index">The index of the Effect to remove</param>
		public virtual void RemoveEffectAt(int index)
		{
			if (Instance.HasValue)
			{
				var effectsComponent = EcsManager.World.GetComponent<EffectsComponent>(Instance.Value);
				if (effectsComponent != null && index >= 0 && index < effectsComponent.Effects.Count)
				{
					var effect = effectsComponent.Effects[index];
					effectsComponent.Effects.RemoveAt(index);
					OnEffectRemoved(new EffectEventArgs(effect));
				}
			}
		}

		/// <summary>
		/// Removes all Effects from the entity
		/// </summary>
		public virtual void RemoveAllEffects()
		{
			if (Instance.HasValue)
			{
				var effectsComponent = EcsManager.World.GetComponent<EffectsComponent>(Instance.Value);
				if (effectsComponent != null)
				{
					var effects = effectsComponent.Effects.ToList();
					effectsComponent.Effects.Clear();
					foreach (var effect in effects)
					{
						OnEffectRemoved(new EffectEventArgs(effect));
					}
				}
			}
		}

		public Room GetInstanceParentRoom()
		{
			if (CacheType != CacheType.Instance || !Instance.HasValue)
				return null;

			var transformComponent = EcsManager.World.GetComponent<TransformComponent>(Instance.Value);
			if (transformComponent?.InstanceParent != null)
			{
				var parentContainer = DataAccess.Get<EntityContainer>(transformComponent.InstanceParent, CacheType.Instance);
				return DataAccess.Get<Room>(parentContainer?.InstanceParent, CacheType.Instance);
			}
			return null;
		}

		public List<Room> GetPrototypeParentRooms()
		{
			var rooms = new List<Room>();
			if (CacheType != CacheType.Prototype || !Instance.HasValue)
				return rooms;

			var transformComponent = EcsManager.World.GetComponent<TransformComponent>(Instance.Value);
			if (transformComponent?.PrototypeParents != null)
			{
				var parentContainers = DataAccess.GetMany<EntityContainer>(transformComponent.PrototypeParents, CacheType.Prototype);
				return DataAccess.GetMany<Room>(parentContainers.Select(r => r.Prototype).Cast<uint>().ToList(), CacheType.Prototype);
			}
			return rooms;
		}

		public Area GetInstanceParentArea()
		{
			if (CacheType != CacheType.Instance)
				return null;

			return GetInstanceParentRoom()?.GetInstanceParentArea();
		}

		public List<Area> GetPrototypeParentAreas()
		{
			var areas = new List<Area>();

			if (CacheType != CacheType.Prototype)
				return areas;

			var parentRooms = GetPrototypeParentRooms();
			foreach (var room in parentRooms)
			{
				var pAreas = room.GetPrototypeParentAreas();
				foreach (var a in pAreas)
					areas.Add(a);
			}

			return areas;
		}

		/// <summary>
		/// Invokes the EffectRemoved event
		/// </summary>
		/// <param name="args">The event args</param>
		protected virtual void OnEffectRemoved(EffectEventArgs args)
		{
			var handler = EffectRemoved;
			if (handler != null)
				handler.Invoke(this, args);
		}

		/// <summary>
		/// Override OnObjectDestroyed to ensure all Effects are removed upon entity deletion
		/// </summary>
		/// <param name="source"></param>
		/// <param name="args"></param>
		protected override void OnObjectDestroyed(object source, CacheObjectEventArgs args)
		{
			RemoveAllEffects();
			
			// Clean up ECS components
			if (Instance.HasValue)
			{
				EcsManager.World.DestroyEntity(Instance.Value);
			}
			
			base.OnObjectDestroyed(source, args);
		}

		/// <summary>
		/// Copies this entity's properties to another entity via components.
		/// </summary>
		/// <param name="entity">The entity to copy to.</param>
		/// <remarks>Doesn't copy IDs or cache type. Use EntityFactory.CreateInstanceFromPrototype for full copies.</remarks>
		public virtual void CopyTo(Entity entity)
		{
			if (entity?.Instance == null || !Instance.HasValue)
				return;

			// Copy component data instead of direct properties
			var sourceIdentity = EcsManager.World.GetComponent<IdentityComponent>(Instance.Value);
			var targetIdentity = EcsManager.World.GetComponent<IdentityComponent>(entity.Instance.Value);

			if (sourceIdentity != null && targetIdentity != null)
			{
				targetIdentity.Name = sourceIdentity.Name;
				targetIdentity.LongDescription = sourceIdentity.LongDescription;
				targetIdentity.ShortDescription = sourceIdentity.ShortDescription;
				targetIdentity.Tier = sourceIdentity.Tier;
				targetIdentity.WasAutoGenerated = sourceIdentity.WasAutoGenerated;
			}
		}

		/// <summary>
		/// Spawns an instance from a prototype using the new ECS system
		/// </summary>
		/// <param name="withEntities">Whether to spawn contained entities</param>
		/// <param name="parent">Parent entity ID</param>
		/// <returns>The spawned entity ID</returns>
		public override uint? Spawn(bool withEntities, uint parent)
		{
			if (CacheType != CacheType.Prototype || !Prototype.HasValue)
				return null;

			return EntityFactory.CreateInstanceFromPrototype(Prototype.Value);
		}

		/// <summary>
		/// Spawns an instance from a prototype using the new ECS system
		/// </summary>
		/// <typeparam name="T">The entity type</typeparam>
		/// <param name="withEntities">Whether to spawn contained entities</param>
		/// <param name="parent">Parent entity ID</param>
		/// <returns>The spawned entity</returns>
		public override T SpawnAsObject<T>(bool withEntities, uint parent)
		{
			var spawnedId = Spawn(withEntities, parent);
			if (spawnedId.HasValue)
			{
				return DataAccess.Get<T>(spawnedId.Value, CacheType.Instance);
			}
			return null;
		}
	}
}