using Hedron.Core.ECS;
using Hedron.Core.ECS.Components;
using Hedron.Core.Entities.Properties;
using Hedron.Core.Damage;
using Hedron.Core.System;
using Hedron.Data;
using System;
using System.Collections.Generic;
using Core.ECS.Properties;
using Core.ECS.Properties.Effects;

namespace Core.ECS
{
	/// <summary>
	/// Factory for creating entities with consistent component compositions based on archetypes
	/// </summary>
	public static class EntityFactory
	{
		/// <summary>
		/// Creates a new entity with components for the specified archetype
		/// </summary>
		/// <param name="archetype">The entity archetype to create</param>
		/// <param name="cacheType">Whether this is a prototype or instance</param>
		/// <param name="name">Optional name for the entity</param>
		/// <returns>The created entity ID</returns>
		public static uint CreateEntity(EntityArchetype archetype, CacheType cacheType, string name = null)
		{
			var world = EcsManager.World;
			var entity = new Entity();
			
			// Add to cache
			var entityId = DataAccess.Add(entity, cacheType);
			entity.Instance = cacheType == CacheType.Instance ? entityId : null;
			entity.Prototype = cacheType == CacheType.Prototype ? entityId : null;

			// Add base components that all entities need
			AddBaseComponents(entityId, name ?? "[unnamed]");

			// Add archetype-specific components
			AddArchetypeComponents(entityId, archetype);

			return entityId;
		}

		/// <summary>
		/// Creates a new entity instance from a prototype
		/// </summary>
		/// <param name="prototypeId">The prototype entity ID</param>
		/// <returns>The created instance entity ID</returns>
		public static uint CreateInstanceFromPrototype(uint prototypeId)
		{
			var world = EcsManager.World;
			var prototype = DataAccess.Get<Entity>(prototypeId, CacheType.Prototype);
			
			if (prototype == null)
				throw new ArgumentException($"Prototype entity {prototypeId} not found");

			// Detect archetype from prototype
			var archetype = ArchetypeRegistry.DetectArchetype(prototypeId, world);
			
			// Create new instance entity
			var instance = new Entity();
			var instanceId = DataAccess.Add(instance, CacheType.Instance);
			instance.Instance = instanceId;
			instance.Prototype = prototypeId;

			// Copy all components from prototype to instance
			CopyComponentsFromPrototype(instanceId, prototypeId, archetype);

			return instanceId;
		}

		/// <summary>
		/// Validates that an entity matches its expected archetype
		/// </summary>
		/// <param name="entityId">The entity ID to validate</param>
		/// <param name="expectedArchetype">The expected archetype</param>
		/// <returns>True if entity matches archetype</returns>
		public static bool ValidateEntityArchetype(uint entityId, EntityArchetype expectedArchetype)
		{
			var definition = ArchetypeRegistry.GetDefinition(expectedArchetype);
			return definition?.ValidateEntity(entityId, EcsManager.World) ?? false;
		}

		/// <summary>
		/// Gets the archetype of an existing entity
		/// </summary>
		/// <param name="entityId">The entity ID</param>
		/// <returns>The detected archetype</returns>
		public static EntityArchetype GetEntityArchetype(uint entityId)
		{
			return ArchetypeRegistry.DetectArchetype(entityId, EcsManager.World);
		}

		/// <summary>
		/// Gets the components required for an archetype
		/// </summary>
		/// <param name="archetype">The archetype</param>
		/// <returns>Set of required component types</returns>
		public static HashSet<Type> GetRequiredComponents(EntityArchetype archetype)
		{
			var definition = ArchetypeRegistry.GetDefinition(archetype);
			return definition?.RequiredComponents ?? new HashSet<Type>();
		}

		private static void AddBaseComponents(uint entityId, string name)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new IdentityComponent
			{
				Name = name,
				ShortDescription = $"A {name.ToLower()}",
				LongDescription = $"You see a {name.ToLower()}.",
				Tier = new Tier { Level = 1 },
				WasAutoGenerated = false
			});

			world.AddComponent(entityId, new TransformComponent
			{
				InstanceParent = null,
				PrototypeParents = new List<uint>()
			});

			world.AddComponent(entityId, new PrototypeComponent
			{
				Instance = null,
				Prototype = null,
				CacheType = CacheType.Prototype
			});

			world.AddComponent(entityId, new EffectsComponent
			{
				Effects = new List<Effect>()
			});
		}

		private static void AddArchetypeComponents(uint entityId, EntityArchetype archetype)
		{
			var world = EcsManager.World;

			switch (archetype)
			{
				case EntityArchetype.Player:
					AddPlayerComponents(entityId);
					break;

				case EntityArchetype.Mob:
					AddMobComponents(entityId);
					break;

				case EntityArchetype.Weapon:
					AddWeaponComponents(entityId);
					break;

				case EntityArchetype.Armor:
					AddArmorComponents(entityId);
					break;

				case EntityArchetype.Potion:
					AddPotionComponents(entityId);
					break;

				case EntityArchetype.StaticItem:
				case EntityArchetype.Consumable:
					AddItemComponents(entityId);
					break;

				case EntityArchetype.Room:
					AddRoomComponents(entityId);
					break;

				case EntityArchetype.Area:
					AddAreaComponents(entityId);
					break;

				case EntityArchetype.World:
				case EntityArchetype.Storage:
				case EntityArchetype.Inventory:
					AddContainerComponents(entityId);
					break;

				case EntityArchetype.Portal:
				case EntityArchetype.Trigger:
					// Base components only for now
					break;

				case EntityArchetype.Custom:
					// No standard components for custom entities
					break;
			}
		}

		private static void AddPlayerComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new AttributesComponent
			{
				Might = 10, Finesse = 10, Will = 10, Intellect = 10, Constitution = 10
			});

			world.AddComponent(entityId, new PoolsComponent
			{
				BaseMaxPools = Pools.Default(),
				CurrentPools = Pools.Default()
			});

			world.AddComponent(entityId, new CurrencyComponent
			{
				Copper = 0, Silver = 0, Gold = 0, Vita = 0, Menta = 0, Astra = 0
			});

			world.AddComponent(entityId, new SkillsComponent
			{
				Skills = new Dictionary<string, int>()
			});

			world.AddComponent(entityId, new QualitiesComponent
			{
				Qualities = new List<string>()
			});

			world.AddComponent(entityId, new InventoryComponent
			{
				Capacity = -1 // Unlimited inventory for players
			});

			world.AddComponent(entityId, new EquipmentComponent());

			world.AddComponent(entityId, new PlayerDataComponent
			{
				ConnectionId = null,
				PrivilegeLevel = 1,
				State = PlayerState.Menu
			});

			world.AddComponent(entityId, new PlayerConfigurationComponent
			{
				Prompt = "> ",
				AutoLook = true
			});
		}

		private static void AddMobComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new AttributesComponent
			{
				Might = 10, Finesse = 10, Will = 10, Intellect = 10, Constitution = 10
			});

			world.AddComponent(entityId, new PoolsComponent
			{
				BaseMaxPools = Pools.Default(),
				CurrentPools = Pools.Default()
			});

			world.AddComponent(entityId, new CurrencyComponent
			{
				Copper = 0, Silver = 0, Gold = 0, Vita = 0, Menta = 0, Astra = 0
			});

			world.AddComponent(entityId, new SkillsComponent
			{
				Skills = new Dictionary<string, int>()
			});

			world.AddComponent(entityId, new QualitiesComponent
			{
				Qualities = new List<string>()
			});

			world.AddComponent(entityId, new InventoryComponent
			{
				Capacity = 50 // Limited inventory for mobs
			});

			world.AddComponent(entityId, new EquipmentComponent());

			world.AddComponent(entityId, new MobDataComponent
			{
				Level = 1,
				BehaviorType = "Passive",
				IsAggressive = false
			});
		}

		private static void AddWeaponComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ItemDataComponent
			{
				Slot = ItemSlot.OneHandedWeapon,
				Rarity = ItemRarity.Common,
				Material = new Material(),
				Value = new Currency { Copper = 100 },
				Behavior = new ItemBehavior { Obtainable = true, Storable = true, RandomDrop = true }
			});

			world.AddComponent(entityId, new WeaponDataComponent
			{
				DamageType = DamageType.Slash,
				MinDamage = Constants.DEFAULT_DAMAGE,
				MaxDamage = Constants.DEFAULT_DAMAGE * 2,
				WeaponType = WeaponType.Sword
			});
		}

		private static void AddArmorComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ItemDataComponent
			{
				Slot = ItemSlot.Body,
				Rarity = ItemRarity.Common,
				Material = new Material(),
				Value = new Currency { Copper = 50 },
				Behavior = new ItemBehavior { Obtainable = true, Storable = true, RandomDrop = true }
			});

			// Note: ArmorDataComponent would be added here when created
		}

		private static void AddPotionComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ItemDataComponent
			{
				Slot = ItemSlot.None,
				Rarity = ItemRarity.Common,
				Material = new Material(),
				Value = new Currency { Copper = 25 },
				Behavior = new ItemBehavior { Obtainable = true, Storable = true }
			});

			world.AddComponent(entityId, new PotionDataComponent
			{
				PoolRestoration = new Pools(),
				Effect = null
			});
		}

		private static void AddItemComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ItemDataComponent
			{
				Slot = ItemSlot.None,
				Rarity = ItemRarity.Common,
				Material = new Material(),
				Value = new Currency { Copper = 10 },
				Behavior = new ItemBehavior { Obtainable = true, Storable = true }
			});
		}

		private static void AddRoomComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ContainerDataComponent
			{
				EntityList = new List<uint>(), // Contains players and mobs in the room
				Capacity = -1,
				AccessType = ContainerAccessType.Public,
				IsOpen = true
			});

			world.AddComponent(entityId, new RoomDataComponent
			{
				Exits = new RoomExits(),
				IsShop = false,
				Environment = "Default",
				IsSafe = false,
				LightLevel = 100
			});

			world.AddComponent(entityId, new InventoryComponent
			{
				Capacity = -1 // Items on the ground in the room
			});
		}

		private static void AddAreaComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ContainerDataComponent
			{
				EntityList = new List<uint>(),
				Capacity = -1,
				AccessType = ContainerAccessType.Public,
				IsOpen = true
			});

			world.AddComponent(entityId, new AreaDataComponent
			{
				RespawnRate = Constants.AREA_MANUAL_RESPAWN,
				SpawnableMobIds = new List<uint>(),
				CuratedItemIds = new List<uint>(),
				AutogeneratedPrototypeMobIds = new List<uint>(),
				Weather = "Clear",
				Temperature = 20,
				PvPEnabled = false,
				DifficultyModifier = 1.0f
			});
		}

		private static void AddContainerComponents(uint entityId)
		{
			var world = EcsManager.World;

			world.AddComponent(entityId, new ContainerDataComponent
			{
				EntityList = new List<uint>(),
				Capacity = -1,
				AccessType = ContainerAccessType.Public,
				IsOpen = true
			});
		}

		private static void CopyComponentsFromPrototype(uint instanceId, uint prototypeId, EntityArchetype archetype)
		{
			var world = EcsManager.World;
			var definition = ArchetypeRegistry.GetDefinition(archetype);

			if (definition == null)
				return;

			foreach (var componentType in definition.RequiredComponents)
			{
				// Get component from prototype and create a copy for instance
				// This is a simplified approach - in a full implementation, you'd want
				// to properly clone/copy component data
				CopyComponentByType(instanceId, prototypeId, componentType);
			}
		}

		private static void CopyComponentByType(uint instanceId, uint prototypeId, Type componentType)
		{
			// This is a simplified implementation
			// In practice, you'd want to implement proper component copying/cloning
			// For now, we'll just re-add the same type of component with default values
			// and let the existing entity wrapper handle the synchronization
		}
	}
}